'From Cuis 5.0 [latest update: #4024] on 17 February 2020 at 2:37:31 pm'!
'Description Turtle geometry operations on a two dimensional plane'!
!provides: 'Turtle-Geometry' 1 0!
SystemOrganization addCategory: #'Turtle-Geometry'!


!classDefinition: #Turtle category: #'Turtle-Geometry'!
Object subclass: #Turtle
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Turtle-Geometry'!
!classDefinition: 'Turtle class' category: #'Turtle-Geometry'!
Turtle class
	instanceVariableNames: ''!


!Turtle commentStamp: '<historical>' prior: 0!
I am a turtle that moves on a two dimensional plane. I have a location point and a movement vector. !
